void nor();
void busy();
void user_login();
void file_exist();
void file_existence();
void call_type();
void call_for();
void dial();
void menu();
void add();
void admin_menu();
//int display_database();
void update_database();
int unregister_user();
void dis();
void display();
void update();
void user_reg();

